### ISSUE TITLE
Is working?

### ISSUE THREAD

**Issue by Lucas559-noob** [burak-aydin/turnitonandoff#3]
Idk when I start the game, on menu it opens the log and in the end I see this 
![Captura de Tela (34)](https://user-images.githubusercontent.com/54007604/94504848-24678c00-01e0-11eb-8562-686f4bc41f83.png)
Log https://gist.github.com/2272d9c7547b015a64c123fb20592a12

**Comment by burak-aydin** [comment]
its normal and it looks like simplesidearms giving warnings not this mod
