### ISSUE TITLE
Mod stopped Working

### ISSUE THREAD

**Issue by green4gfx** [burak-aydin/turnitonandoff#4]
Hi the Mod stopped working as I reconiced after Loading my Save game, it worked before without problems. It looks like all electrics are excluded, here's one Log line:

```
Excluded PowerUser:StandingLamp
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
TurnItOnandOff.TurnItOnandOff:initPowerValues ()
TurnItOnandOff.TurnItOnandOff:SettingsChanged ()
HugsLib.HugsLibController:OnBeforeModSettingsSaved ()
HugsLib.Settings.ModSettingsManager:SaveChanges ()
HugsLib.Settings.Dialog_ModSettings:PostClose ()
Verse.WindowStack:TryRemove (Verse.Window,bool)
Verse.Window:Close (bool)
HugsLib.Settings.Dialog_ModSettings:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
```
Full Log in Text file:
[turn-on-off-problem.txt](https://github.com/burak-aydin/turnitonandoff/files/10280535/turn-on-off-problem.txt)

**Comment by burak-aydin** [comment]
thanks for the report, it looks like an update broke it.

**Comment by burak-aydin** [comment]
Mod works fine, a bug on base game causes UI to display incorrect information. Its fixed in the last unstable build.
